panier_homepage:
    path:     /
    defaults: { _controller: PanierBundle:Default:index }
panier_trade:
    path:     /trade/
    defaults: { _controller: PanierBundle:Panier:trade }
panier_cart:
    path:     /cart
    defaults: { _controller: PanierBundle:Panier:index }
cart_add:
    path:     /add/{id}
    defaults: { _controller: PanierBundle:Panier:add }
cart_order:
    path:     /order
    defaults: { _controller: PanierBundle:Panier:Order }
cart_orderCreate:
    path:     /Createorder
    defaults: { _controller: PanierBundle:Panier:CreateOrder }
cart_Creation:
    path:     /Creation
    defaults: { _controller: PanierBundle:Panier:CreateOrder }
cart_pdf:
    path:     /pdf/{id}
    defaults: { _controller: PanierBundle:Panier:PDF }
cart_addSup:
    path:     /addSup/{id}
    defaults: { _controller: PanierBundle:Panier:addSup }
cart_addM:
    path:     /addM/{id}
    defaults: { _controller: PanierBundle:Panier:addM }
cart_show:
    path:     /show/
    defaults: { _controller: PanierBundle:Panier:index}
cartPage_show:
    path:     /showPage
    defaults: { _controller: PanierBundle:Panier:showCart }
cart_delete:
     path:     /delete_cart/{id}
     defaults: { _controller: PanierBundle:Panier:RemoveCart }
call:
    path:     /call
    defaults: { _controller: PanierBundle:Panier:call }
findLC:
    path:     /findLC/{id}
    defaults: { _controller: PanierBundle:Panier:findLC }
findC:
    path:     /findC/{id}
    defaults: { _controller: PanierBundle:Panier:HistoryCmd }
test:
    path:     /test
    defaults: { _controller: PanierBundle:Panier:test }
