panier:
    resource: "@PanierBundle/Resources/config/routing.yml"
    prefix:   /panier

magasin:
    resource: "@MagasinBundle/Resources/config/routing.yml"
    prefix:   /magasin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
    prefix:   /produit

app:
    resource: '@AppBundle/Controller/'
    type: annotation
